/* KinStudy Pro v6 — browser-first, offline-capable build.
   WebLLM is pinned to 0.2.82 because 0.2.83/0.2.84 introduced a reported
   shape-cache regression that can produce "Object has already been disposed".
   SmolVLM 500M remains a separate Transformers.js vision runtime.
*/

const WEBLLM_URL = "https://esm.run/@mlc-ai/web-llm@0.2.82";
const TRANSFORMERS_URL = "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2";
const PDFJS_URL = "https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.min.mjs";
const PDFJS_WORKER_URL = "https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.worker.min.mjs";

let webllm = null;
let transformers = null;
let pdfjs = null;

const $ = id => document.getElementById(id);
const ids = ["sidebar","closeSidebarBtn","newChatBtn","chatList","themeBtn","settingsBtn","menuBtn","chatTitle","connectionText","modeSelect","modelSelect","codeModeBtn","offlinePanel","webgpuStatus","loadModelBtn","freeModelBtn","modelProgress","modelProgressText","offlineReadyText","messages","welcome","fileInput","attachBtn","promptInput","stopBtn","sendBtn","tokenEstimate","attachmentCard","attachmentName","attachmentStatus","clearAttachmentBtn","settingsModal","closeSettingsBtn","apiKeyInput","instructionsInput","thinkingSelect","exportBtn","saveSettingsBtn","toast"];
const els = Object.fromEntries(ids.map(id => [id, $(id)]));

const ONLINE_MODELS = [
  { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash" },
  { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash" },
  { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" }
];

const OFFLINE_WANTED = [
  { key:"smol360", name:"SmolLM2 360M", patterns:[/^SmolLM2-360M-Instruct-q4f16_1-MLC$/i,/^SmolLM2-360M-Instruct-q0f16-MLC$/i,/^SmolLM2-360M-Instruct-q4f32_1-MLC$/i] },
  { key:"qwen05", name:"Qwen 2.5 0.5B Instruct", patterns:[/^Qwen2\.5-0\.5B-Instruct-q4f16_1-MLC$/i] },
  { key:"qwen15", name:"Qwen 2.5 1.5B Instruct", patterns:[/^Qwen2\.5-1\.5B-Instruct-q4f16_1-MLC$/i] },
  { key:"coder15", name:"Qwen 2.5 Coder 1.5B", patterns:[/^Qwen2\.5-Coder-1\.5B-Instruct-q4f16_1-MLC$/i] }
];
const VISION_MODEL = { key:"smolvlm500", name:"SmolVLM 500M • Vision", id:"HuggingFaceTB/SmolVLM-500M-Instruct" };
const DEFAULT_INSTRUCTIONS = "You are KinStudy Pro, a helpful study and coding assistant. Explain accurately, show steps when useful, do not invent facts, and distinguish uncertainty. Use verified study context only when relevant.";
const CHAT_DB = "kinstudy-chat-v6";
const FILE_DB = "kinstudy-files-v2";
const CHAT_STORE = "chats";

let state = {
  chats: [], currentId:null,
  theme:localStorage.getItem("ks_theme")||"dark",
  mode:localStorage.getItem("ks_mode")||"online",
  onlineModel:localStorage.getItem("ks_online_model")||ONLINE_MODELS[0].id,
  offlineKey:localStorage.getItem("ks_offline_key")||"smol360",
  apiKey:localStorage.getItem("ks_api_key")||"",
  instructions:localStorage.getItem("ks_instructions")||DEFAULT_INSTRUCTIONS,
  thinking:localStorage.getItem("ks_thinking")||"medium",
  codeMode:localStorage.getItem("ks_code_mode")==="1",
  attachment:null,
  studyData:[],
  engine:null,
  loadedModelId:null,
  engineBusy:false,
  generating:false,
  aborter:null,
  webgpu:false,
  offlineCatalog:[],
  visionPipe:null,
  visionLoaded:false,
  runtimesReady:false,
  offlineStorageReady:false,
  libraryLoading:false
};

function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function toast(msg,ms=3000){els.toast.textContent=msg;els.toast.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.add("hidden"),ms)}
function escapeHtml(s=""){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function setTheme(theme){state.theme=theme;document.documentElement.dataset.theme=theme;localStorage.setItem("ks_theme",theme);const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=theme==="light"?"#f7f8fb":"#0b0d12"}
function setConnection(s){els.connectionText.textContent=s}
function estimateTokens(t=""){return Math.ceil(String(t).length/4)}
function updateTokenEstimate(){let n=estimateTokens(els.promptInput.value);if(state.attachment?.text)n+=estimateTokens(state.attachment.text);els.tokenEstimate.textContent=`~${n.toLocaleString()} tokens`}
function autoGrow(){els.promptInput.style.height="auto";els.promptInput.style.height=Math.min(180,els.promptInput.scrollHeight)+"px"}
function friendlyError(e){const s=String(e?.message||e||"Unknown error");if(/already been disposed|already disposed|module has already been disposed|device.*lost|device.*removed|out of memory|allocation failed/i.test(s))return `${s} The local GPU engine became unstable. Free RAM, then Load Engine again; if it repeats, use SmolLM2 360M.`;if(/failed to fetch|network|offline/i.test(s))return `${s} The required runtime/model is not cached yet. Open KinStudy once online and finish the first model load.`;return s}

/* ---------- Persistent chat storage ---------- */
function openChatDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(CHAT_DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(CHAT_STORE))db.createObjectStore(CHAT_STORE,{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function persistChats(){try{const db=await openChatDB();await new Promise((res,rej)=>{const tx=db.transaction(CHAT_STORE,"readwrite");const st=tx.objectStore(CHAT_STORE);for(const c of state.chats)st.put(c);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});localStorage.setItem("ks_current_chat",state.currentId||"")}catch(e){localStorage.setItem("ks_chats_v6",JSON.stringify(state.chats));localStorage.setItem("ks_current_chat",state.currentId||"")}}
async function loadChats(){try{const db=await openChatDB();state.chats=await new Promise((res,rej)=>{const tx=db.transaction(CHAT_STORE,"readonly");const req=tx.objectStore(CHAT_STORE).getAll();req.onsuccess=()=>res(req.result||[]);req.onerror=()=>rej(req.error)});}catch{try{state.chats=JSON.parse(localStorage.getItem("ks_chats_v6")||"[]")}catch{state.chats=[]}}if(!state.chats.length)newChat(false);else state.currentId=localStorage.getItem("ks_current_chat")||state.chats[0].id}
function currentChat(){return state.chats.find(c=>c.id===state.currentId)}
function newChat(save=true){const chat={id:uid(),title:"New chat",messages:[],summary:""};state.chats.unshift(chat);state.currentId=chat.id;localStorage.setItem("ks_current_chat",state.currentId);renderChatList();renderMessages();if(save)persistChats();if(innerWidth<=820)els.sidebar.classList.remove("open")}
function renderChatList(){els.chatList.innerHTML=state.chats.map(c=>`<div class="chat-item ${c.id===state.currentId?"active":""}"><button class="chat-open" data-chat="${c.id}">${escapeHtml(c.title||"New chat")}</button><button class="chat-delete" data-delete="${c.id}" aria-label="Delete chat">×</button></div>`).join("");els.chatList.querySelectorAll("[data-chat]").forEach(b=>b.onclick=()=>{state.currentId=b.dataset.chat;localStorage.setItem("ks_current_chat",state.currentId);renderChatList();renderMessages()});els.chatList.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{const id=b.dataset.delete;state.chats=state.chats.filter(c=>c.id!==id);if(!state.chats.length)newChat(false);else if(state.currentId===id)state.currentId=state.chats[0].id;await persistChats();renderChatList();renderMessages()})}

/* ---------- Lightweight Markdown renderer; no CDN dependency ---------- */
function inlineMd(s){return escapeHtml(s).replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/\*([^*]+)\*/g,"<em>$1</em>").replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>')}
function renderMarkdown(src=""){const text=String(src).replace(/\r/g,"");const blocks=text.split(/```/);let html="";for(let i=0;i<blocks.length;i++){if(i%2===1){let code=blocks[i].replace(/^\w+\n/,"");html+=`<pre><code>${escapeHtml(code)}</code></pre>`;continue}const lines=blocks[i].split("\n");let inList=false;for(const line of lines){if(/^\s*[-*]\s+/.test(line)){if(!inList){html+="<ul>";inList=true}html+=`<li>${inlineMd(line.replace(/^\s*[-*]\s+/,""))}</li>`}else{if(inList){html+="</ul>";inList=false}if(!line.trim())html+="<br>";else if(/^###\s+/.test(line))html+=`<h3>${inlineMd(line.replace(/^###\s+/,""))}</h3>`;else if(/^##\s+/.test(line))html+=`<h2>${inlineMd(line.replace(/^##\s+/,""))}</h2>`;else if(/^#\s+/.test(line))html+=`<h1>${inlineMd(line.replace(/^#\s+/,""))}</h1>`;else html+=`<p>${inlineMd(line)}</p>`}}if(inList)html+="</ul>"}return html}
async function copyText(text,btn){try{await navigator.clipboard.writeText(text);btn.textContent="Copied"}catch{const ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove();btn.textContent="Copied"}setTimeout(()=>btn.textContent=btn.dataset.label||"Copy",1200)}
function addMessageActions(wrap,m){if(m.role!=="assistant")return;const actions=document.createElement("div");actions.className="message-actions";const copy=document.createElement("button");copy.className="copy-answer";copy.dataset.label="Copy";copy.textContent="Copy";copy.onclick=()=>copyText(m.content||"",copy);actions.appendChild(copy);wrap.querySelector(".message-body").appendChild(actions)}
function addCodeButtons(wrap){wrap.querySelectorAll("pre").forEach(pre=>{if(pre.querySelector(".copy-code"))return;const btn=document.createElement("button");btn.className="copy-code";btn.dataset.label="Copy code";btn.textContent="Copy code";btn.onclick=()=>copyText(pre.querySelector("code")?.innerText||pre.innerText,btn);pre.appendChild(btn)})}
function appendMessage(m){const wrap=document.createElement("article");wrap.className=`message ${m.role}`;wrap.dataset.messageId=m.id;wrap.innerHTML=`<div class="avatar">${m.role==="user"?"Y":"K"}</div><div class="message-body"><div class="message-head">${m.role==="user"?"You":"KinStudy"}</div><div class="message-content">${renderMarkdown(m.content||"")}</div>${m.attachmentName?`<div class="attachment-inline">📎 ${escapeHtml(m.attachmentName)}</div>`:""}</div>`;els.messages.appendChild(wrap);addCodeButtons(wrap);addMessageActions(wrap,m);return wrap}
function updateMessage(m){const el=els.messages.querySelector(`[data-message-id="${CSS.escape(m.id)}"]`);if(!el)return;el.querySelector(".message-content").innerHTML=renderMarkdown(m.content||"");addCodeButtons(el);el.querySelector(".message-actions")?.remove();addMessageActions(el,m);scrollBottom()}
function renderMessages(){const c=currentChat();els.chatTitle.textContent=c?.title||"New chat";els.messages.querySelectorAll(".message").forEach(x=>x.remove());if(!c?.messages?.length){els.welcome.classList.remove("hidden");return}els.welcome.classList.add("hidden");for(const m of c.messages)appendMessage(m);scrollBottom()}
function scrollBottom(){requestAnimationFrame(()=>els.messages.scrollTop=els.messages.scrollHeight)}

/* ---------- Runtime loading ---------- */
async function loadRuntimes(){if(state.runtimesReady)return true;if(state.libraryLoading)return false;state.libraryLoading=true;try{setConnection("Preparing local AI runtime…");webllm=await import(WEBLLM_URL);transformers=await import(TRANSFORMERS_URL);state.runtimesReady=true;resolveOfflineCatalog();populateModels();return true}catch(e){console.warn("Runtime load failed",e);state.runtimesReady=false;setConnection("Offline runtime not cached yet");toast("AI runtime is not cached. Connect once and reload KinStudy to prepare offline mode.",6000);return false}finally{state.libraryLoading=false}}
function resolveOfflineCatalog(){const list=webllm?.prebuiltAppConfig?.model_list||[];state.offlineCatalog=OFFLINE_WANTED.map(w=>{let found=null;for(const m of list){const id=String(m.model_id||"");if(w.patterns.some(p=>p.test(id))){found=m;break}}return found?{...w,model:found}:null}).filter(Boolean)}
function populateModels(){if(!els.modelSelect)return;els.modelSelect.innerHTML="";if(state.mode==="online"){for(const m of ONLINE_MODELS){const o=document.createElement("option");o.value=m.id;o.textContent=m.name;els.modelSelect.appendChild(o)}els.modelSelect.value=ONLINE_MODELS.some(m=>m.id===state.onlineModel)?state.onlineModel:ONLINE_MODELS[0].id;els.offlinePanel.classList.add("hidden");return}for(const m of state.offlineCatalog){const o=document.createElement("option");o.value=m.key;o.textContent=`🧠 ${m.name}`;els.modelSelect.appendChild(o)}const v=document.createElement("option");v.value=VISION_MODEL.key;v.textContent="👁️ SmolVLM 500M • Vision";els.modelSelect.appendChild(v);const keys=[...state.offlineCatalog.map(x=>x.key),VISION_MODEL.key];state.offlineKey=keys.includes(state.offlineKey)?state.offlineKey:(state.offlineCatalog[0]?.key||VISION_MODEL.key);els.modelSelect.value=state.offlineKey;els.offlinePanel.classList.remove("hidden");updateOfflinePanel()}
function selectedOfflineEntry(){if(state.offlineKey===VISION_MODEL.key)return VISION_MODEL;return state.offlineCatalog.find(x=>x.key===state.offlineKey)?.model||null}
function updateOfflinePanel(){const vision=state.offlineKey===VISION_MODEL.key;els.freeModelBtn.disabled=vision?!state.visionLoaded:!state.engine;els.loadModelBtn.disabled=state.engineBusy||!state.runtimesReady;if(!state.runtimesReady){els.webgpuStatus.textContent="Runtime not ready — connect once to cache it";els.modelProgressText.textContent="The UI is available offline, but the AI runtime must have been cached during a previous online session.";return}els.webgpuStatus.textContent=state.webgpu?`WebGPU detected • ${vision?"vision":"text"}`:"WebGPU not detected";els.modelProgressText.textContent=vision?(state.visionLoaded?"SmolVLM 500M is loaded.":"Load SmolVLM 500M for offline image/video understanding."):(state.loadedModelId?`Loaded: ${state.loadedModelId}`:"Choose a model, then Load Engine.")}
async function checkWebGPU(){try{state.webgpu=!!navigator.gpu;if(navigator.storage?.persist)state.offlineStorageReady=await navigator.storage.persist();}catch{state.webgpu=false}els.webgpuStatus.textContent=state.webgpu?"WebGPU detected":"WebGPU not detected";updateOfflineReady()}
async function updateOfflineReady(){let cacheOk=false;try{if(navigator.storage?.estimate){const q=await navigator.storage.estimate();cacheOk=!!q.quota}}catch{}state.offlineStorageReady=state.offlineStorageReady||cacheOk;els.offlineReadyText.textContent=state.offlineStorageReady?"Offline storage: available — models remain in browser storage after download.":"Offline storage: browser persistence could not be confirmed."}

/* ---------- Model lifecycle ---------- */
async function disposeTextEngine(){const e=state.engine;state.engine=null;state.loadedModelId=null;if(!e)return;try{await e.unload?.()}catch{}try{await e.terminate?.()}catch{}try{await e.dispose?.()}catch{}}
async function disposeVision(){const p=state.visionPipe;state.visionPipe=null;state.visionLoaded=false;if(!p)return;try{await p.dispose?.()}catch{}}
async function freeOfflineModel(show=true){await disposeTextEngine();await disposeVision();els.modelProgress.style.width="0%";els.modelProgressText.textContent="Engine freed. Choose a model and Load Engine.";setConnection("Offline • engine not loaded");updateOfflinePanel();if(show)toast("Engine freed — chat history is still saved.")}
async function loadOfflineModel(){if(!await loadRuntimes())return;if(state.offlineKey===VISION_MODEL.key)return loadVision();const entry=state.offlineCatalog.find(x=>x.key===state.offlineKey);if(!entry){toast("This model is not in the pinned WebLLM catalog.",5000);return}if(!state.webgpu){toast("WebGPU is unavailable in this browser/device. WebLLM text models need WebGPU.",5000);return}if(state.loadedModelId===entry.model.model_id&&state.engine)return;await disposeVision();if(state.engine)await disposeTextEngine();state.engineBusy=true;els.loadModelBtn.disabled=true;els.modelProgress.style.width="0%";els.modelProgressText.textContent=`Loading ${entry.name}…`;
try{state.engine=await webllm.CreateMLCEngine(entry.model.model_id,{appConfig:{...webllm.prebuiltAppConfig,cacheBackend:"indexeddb"},initProgressCallback:p=>{const pct=Math.round((p.progress||0)*100);els.modelProgress.style.width=`${pct}%`;els.modelProgressText.textContent=p.text||`Loading… ${pct}%`}}, {context_window_size:4096});state.loadedModelId=entry.model.model_id;els.modelProgress.style.width="100%";toast(`${entry.name} loaded and cached`);setConnection(`Offline • ${entry.name}`)}catch(e){state.engine=null;state.loadedModelId=null;console.error(e);toast(`Could not load ${entry.name}: ${friendlyError(e)}`,7000);setConnection("Offline • engine not loaded")}finally{state.engineBusy=false;updateOfflinePanel()}}
async function loadVision(){if(!await loadRuntimes())return;if(state.visionLoaded)return;if(state.engine)await disposeTextEngine();state.engineBusy=true;els.loadModelBtn.disabled=true;els.modelProgress.style.width="2%";els.modelProgressText.textContent="Loading SmolVLM 500M… first load must finish online.";try{const {pipeline,env}=transformers;env.allowLocalModels=false;env.useBrowserCache=true;state.visionPipe=await pipeline("image-text-to-text",VISION_MODEL.id,{device:state.webgpu?"webgpu":"wasm",dtype:"q4",progress_callback:p=>{const pct=p.total?Math.min(99,Math.round((p.loaded||0)/p.total*100)):2;els.modelProgress.style.width=`${pct}%`;els.modelProgressText.textContent=p.status?`${p.status} ${pct}%`:`Loading SmolVLM 500M… ${pct}%`}});state.visionLoaded=true;els.modelProgress.style.width="100%";els.modelProgressText.textContent="SmolVLM 500M is loaded and cached.";toast("SmolVLM 500M loaded and cached");setConnection("Offline • SmolVLM 500M")}catch(e){await disposeVision();toast(`SmolVLM failed to load: ${friendlyError(e)}`,7000);console.error(e)}finally{state.engineBusy=false;updateOfflinePanel()}}

/* ---------- Study data / files ---------- */
async function loadStudyData(){try{const r=await fetch("./study-data.json");if(r.ok){const j=await r.json();state.studyData=j.entries||[]}}catch(e){console.warn(e)}}
function relevantStudy(text){const q=String(text).toLowerCase();return state.studyData.filter(e=>{const hay=[e.title,e.subject,e.topic,e.keywords?.join(" "),e.content].join(" ").toLowerCase();return q.split(/\W+/).filter(x=>x.length>3).some(w=>hay.includes(w))}).slice(0,4)}
function buildSystem(userText){const rel=relevantStudy(userText);let s=state.instructions||DEFAULT_INSTRUCTIONS;if(state.codeMode)s+="\n\nCODE MODE: prioritize correct runnable code, explain key decisions briefly, preserve syntax, and use longer answers when the task requires code.";if(rel.length)s+=`\n\nVerified study context. Use only when relevant:\n${rel.map(x=>`- ${x.title}: ${x.content}`).join("\n")}`;return s}
function openFileDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(FILE_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains("files"))r.result.createObjectStore("files",{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveFileLocally(){if(!state.attachment?.file){toast("Attach a file first.");return}try{const db=await openFileDB();await new Promise((res,rej)=>{const tx=db.transaction("files","readwrite");tx.objectStore("files").put({id:uid(),name:state.attachment.name,type:state.attachment.type,blob:state.attachment.file,created:Date.now()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});toast("File saved locally")}catch{toast("Local file storage is unavailable.")}}
async function parseFile(file){if(!file)return null;const type=file.type||"",name=file.name||"file";els.attachmentCard.classList.remove("hidden");els.attachmentName.textContent=name;els.attachmentStatus.textContent="Reading…";if(type.startsWith("image/"))return {name,type,kind:"image",file};if(type.startsWith("video/"))return {name,type,kind:"video",file};if(type==="application/pdf"||name.toLowerCase().endsWith(".pdf")){if(!pdfjs)pdfjs=await import(PDFJS_URL);pdfjs.GlobalWorkerOptions.workerSrc=PDFJS_WORKER_URL;const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text="";for(let i=1;i<=pdf.numPages;i++){els.attachmentStatus.textContent=`Reading PDF: Page ${i} of ${pdf.numPages}…`;const page=await pdf.getPage(i);const c=await page.getTextContent();text+=`\n[Page ${i}]\n`+c.items.map(x=>x.str).join(" ")}els.attachmentStatus.textContent="PDF text extracted";return {name,type,kind:"pdf",file,text:text.trim()}}const text=await file.text();return {name,type,kind:"text",file,text:text.slice(0,180000)}}
async function handleFile(file){try{state.attachment=await parseFile(file);els.attachmentStatus.textContent=state.attachment.kind==="pdf"?"PDF text extracted":"Ready";updateTokenEstimate();toast(`${file.name} attached`)}catch(e){clearAttachment();toast(`File error: ${friendlyError(e)}`,5000)}}
function clearAttachment(){state.attachment=null;els.fileInput.value="";els.attachmentCard.classList.add("hidden");els.attachmentName.textContent="";els.attachmentStatus.textContent="";updateTokenEstimate()}
async function imageToDataURL(file){return new Promise((resolve,reject)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{const max=1280,scale=Math.min(1,max/img.width,max/img.height),c=document.createElement("canvas");c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext("2d").drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(u);resolve(c.toDataURL("image/jpeg",.82))};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error("Image could not be decoded."))};img.src=u})}
async function videoFrames(file,count=4){const url=URL.createObjectURL(file),v=document.createElement("video");v.src=url;v.muted=true;v.playsInline=true;await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=()=>rej(new Error("Video could not be opened."))});const out=[],d=Number.isFinite(v.duration)?v.duration:0;for(let i=0;i<count;i++){const t=d*(i+1)/(count+1);await new Promise((res,rej)=>{const ok=()=>{v.onseeked=null;v.onerror=null;res()};v.onseeked=ok;v.onerror=()=>rej(new Error("Could not seek video."));v.currentTime=t});const c=document.createElement("canvas"),scale=Math.min(1,1280/v.videoWidth,1280/v.videoHeight);c.width=Math.max(1,Math.round(v.videoWidth*scale));c.height=Math.max(1,Math.round(v.videoHeight*scale));c.getContext("2d").drawImage(v,0,0,c.width,c.height);out.push(c.toDataURL("image/jpeg",.8))}URL.revokeObjectURL(url);return out}

/* ---------- Conversation compaction ---------- */
function isCodeLike(text){return state.codeMode||/```|\b(code|coding|program|javascript|typescript|python|html|css|react|sql|api|function|class|debug|bug|error|async|await)\b/i.test(text)}
function compactHistory(c,maxChars=9000){const all=c.messages||[];if(all.length<=8&&all.reduce((n,m)=>n+m.content.length,0)<=maxChars)return;const keep=all.slice(-6);const old=all.slice(0,-6);const digest=old.map(m=>`${m.role}: ${m.content.slice(0,900)}`).join("\n");c.summary=((c.summary?c.summary+"\n":"")+digest).slice(-5000);c.messages=keep}
function buildOfflineMessages(c,prompt,attachment){compactHistory(c,isCodeLike(prompt)?12000:9000);const msgs=[{role:"system",content:buildSystem(prompt)}];if(c.summary)msgs.push({role:"system",content:`Conversation memory summary (older messages):\n${c.summary}`});const recent=c.messages.filter(m=>m.content);for(const m of recent){msgs.push({role:m.role,content:m.content})}let user=prompt;if(attachment?.text)user+=`\n\nAttached file (${attachment.name}):\n${attachment.text.slice(0,90000)}`;if(!recent.length||recent[recent.length-1].role!=="user"||recent[recent.length-1].content!==user)msgs.push({role:"user",content:user});return msgs}

/* ---------- AI generation ---------- */
function buildOnlineContents(c,prompt,attachment){const out=[];for(const m of (c.messages||[])){if(!m.content)continue;out.push({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]})}let parts=[{text:prompt||"Analyze the attachment."}];if(attachment?.text)parts.push({text:`\n\nAttached file (${attachment.name}):\n${attachment.text}`});if(!out.length||out[out.length-1].role!=="user"||out[out.length-1].parts?.[0]?.text!==prompt)out.push({role:"user",parts});return out}
async function generateOnline(prompt,msg,attachment,c){if(!state.apiKey)throw new Error("Add your Gemini API key in Settings first.");const system=buildSystem(prompt)+(c.summary?`\n\nConversation memory summary:\n${c.summary}`:"");const body={system_instruction:{parts:[{text:system}]},contents:buildOnlineContents(c,prompt,attachment),generationConfig:{thinkingConfig:{thinkingLevel:state.thinking}}};const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(state.onlineModel)}:streamGenerateContent?alt=sse&key=${encodeURIComponent(state.apiKey)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:state.aborter.signal});if(!r.ok)throw new Error(`Gemini API ${r.status}: ${(await r.text()).slice(0,500)}`);const reader=r.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.startsWith("data:"))continue;const raw=line.slice(5).trim();if(!raw||raw==="[DONE]")continue;try{const j=JSON.parse(raw),parts=j.candidates?.[0]?.content?.parts||[];for(const p of parts)if(p.text){msg.content+=p.text;updateMessage(msg)}}catch{}}}}
async function generateOffline(prompt,msg,attachment,c){if(state.offlineKey===VISION_MODEL.key){if(!attachment||!['image','video'].includes(attachment.kind))throw new Error("Select an image or video for SmolVLM 500M.");if(!state.visionLoaded)await loadVision();const images=attachment.kind==="image"?[await imageToDataURL(attachment.file)]:await videoFrames(attachment.file,4);let answer="";for(let i=0;i<images.length;i++){els.modelProgressText.textContent=`Analyzing ${attachment.kind} ${i+1} of ${images.length}…`;const result=await state.visionPipe([{role:"user",content:[{type:"image",url:images[i]},{type:"text",text:prompt||"Analyze this for a student and explain what you see."}]}],{max_new_tokens:600});answer+=`${images.length>1?`Frame ${i+1}: `:""}${extractVisionText(result)}\n\n`}msg.content=answer.trim();updateMessage(msg);return}
if(!state.engine)throw new Error("Load an offline text model first.");const messages=buildOfflineMessages(c,prompt,attachment);const maxTokens=isCodeLike(prompt)?1800:900;try{const stream=await state.engine.chat.completions.create({messages,temperature:.35,max_tokens:maxTokens,stream:true});for await(const chunk of stream){if(state.aborter?.signal.aborted)break;const piece=chunk.choices?.[0]?.delta?.content||"";if(piece){msg.content+=piece;updateMessage(msg)}}}catch(e){if(/already disposed|device.*lost|device.*removed|out of memory/i.test(String(e))){await disposeTextEngine();throw new Error(`The GPU engine became unstable during generation. The conversation is saved. Reload the same model and retry. Original: ${e.message||e}`)}throw e}}
function extractVisionText(r){if(typeof r==="string")return r;if(Array.isArray(r)){const x=r.at(-1);if(typeof x==="string")return x;return x?.generated_text||x?.text||JSON.stringify(x)}return r?.generated_text||r?.text||JSON.stringify(r)}

async function sendMessage(prefill=null){if(state.generating||state.engineBusy)return;const text=(prefill??els.promptInput.value).trim();if(!text&&!state.attachment)return;const attachment=state.attachment,c=currentChat();if(c.messages.length===0)c.title=(text||attachment?.name||"New chat").slice(0,42);const user={id:uid(),role:"user",content:text||"Analyze this file.",attachmentName:attachment?.name||null};c.messages.push(user);appendMessage(user);const msg={id:uid(),role:"assistant",content:""};c.messages.push(msg);appendMessage(msg);await persistChats();renderChatList();els.promptInput.value="";autoGrow();updateTokenEstimate();state.generating=true;state.aborter=new AbortController();els.sendBtn.disabled=true;els.stopBtn.classList.remove("hidden");setConnection(state.mode==="online"?"Generating online…":"Generating locally…");try{if(state.mode==="online")await generateOnline(text,msg,attachment,c);else await generateOffline(text,msg,attachment,c);if(!msg.content)msg.content="No text response was returned."}catch(e){if(e.name==="AbortError")msg.content+=(msg.content?"\n\n":"")+"_Generation stopped._";else msg.content+=(msg.content?"\n\n":"")+`**Error:** ${friendlyError(e)}`;console.error(e)}finally{state.generating=false;state.aborter=null;els.sendBtn.disabled=false;els.stopBtn.classList.add("hidden");updateMessage(msg);await persistChats();clearAttachment();updateOfflinePanel();setConnection(state.mode==="online"?"Online • Gemini":`Offline • ${state.loadedModelId||VISION_MODEL.name}`)}}
function stopGeneration(){state.aborter?.abort();try{state.engine?.interruptGenerate?.()}catch{}}

/* ---------- Settings / offline boot ---------- */
function openSettings(){els.apiKeyInput.value=state.apiKey;els.instructionsInput.value=state.instructions;els.thinkingSelect.value=state.thinking;els.settingsModal.classList.remove("hidden")}
function saveSettings(){state.apiKey=els.apiKeyInput.value.trim();state.instructions=els.instructionsInput.value.trim()||DEFAULT_INSTRUCTIONS;state.thinking=els.thinkingSelect.value;localStorage.setItem("ks_api_key",state.apiKey);localStorage.setItem("ks_instructions",state.instructions);localStorage.setItem("ks_thinking",state.thinking);els.settingsModal.classList.add("hidden");toast("Settings saved")}
function exportChat(){const c=currentChat();const md=`# ${c.title}\n\n`+(c.messages||[]).map(m=>`## ${m.role==="user"?"You":"KinStudy"}\n\n${m.content}`).join("\n\n");const blob=new Blob([md],{type:"text/markdown"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${(c.title||"kinstudy-chat").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"")||"kinstudy-chat"}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function setCodeMode(on){state.codeMode=!!on;els.codeModeBtn.setAttribute("aria-pressed",String(state.codeMode));localStorage.setItem("ks_code_mode",state.codeMode?"1":"0");toast(state.codeMode?"Code mode on — longer local responses":"Code mode off")}
async function warmOfflineCaches(){if(!navigator.onLine)return;try{await caches.open("kinstudy-runtime-v6");}catch{}updateOfflineReady()}
function bind(){els.newChatBtn.onclick=()=>newChat();els.menuBtn.onclick=()=>els.sidebar.classList.add("open");els.closeSidebarBtn.onclick=()=>els.sidebar.classList.remove("open");els.themeBtn.onclick=()=>setTheme(state.theme==="dark"?"light":"dark");els.settingsBtn.onclick=openSettings;els.closeSettingsBtn.onclick=()=>els.settingsModal.classList.add("hidden");els.saveSettingsBtn.onclick=saveSettings;els.exportBtn.onclick=exportChat;els.settingsModal.onclick=e=>{if(e.target===els.settingsModal)els.settingsModal.classList.add("hidden")};els.attachBtn.onclick=()=>els.fileInput.click();els.fileInput.onchange=()=>handleFile(els.fileInput.files[0]);els.clearAttachmentBtn.onclick=clearAttachment;els.sendBtn.onclick=()=>sendMessage();els.stopBtn.onclick=stopGeneration;els.promptInput.oninput=()=>{autoGrow();updateTokenEstimate()};els.promptInput.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}};document.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>sendMessage(b.dataset.prompt));els.codeModeBtn.onclick=()=>setCodeMode(!state.codeMode);
els.modeSelect.onchange=async()=>{if(state.generating)return;await freeOfflineModel(false);state.mode=els.modeSelect.value;localStorage.setItem("ks_mode",state.mode);populateModels();setConnection(state.mode==="online"?"Online • Gemini":"Offline • runtime ready when cached")};els.modelSelect.onchange=async()=>{if(state.generating)return;if(state.mode==="online"){state.onlineModel=els.modelSelect.value;localStorage.setItem("ks_online_model",state.onlineModel)}else{await freeOfflineModel(false);state.offlineKey=els.modelSelect.value;localStorage.setItem("ks_offline_key",state.offlineKey);updateOfflinePanel()}};els.loadModelBtn.onclick=loadOfflineModel;els.freeModelBtn.onclick=()=>freeOfflineModel(true)}
async function registerSW(){if(!("serviceWorker" in navigator)||!/^https?:$/.test(location.protocol))return;try{const reg=await navigator.serviceWorker.register("./sw.js?v=6",{scope:"./"});if(reg.waiting)reg.waiting.postMessage({type:"SKIP_WAITING"});await navigator.serviceWorker.ready;console.log("KinStudy SW ready")}catch(e){console.warn("SW",e)}}
window.addEventListener("online",()=>{setConnection(state.mode==="online"?"Online • Gemini":"Offline • cached runtime available");warmOfflineCaches()});window.addEventListener("offline",()=>setConnection("Offline • browser cache only"));

async function init(){setTheme(state.theme);setCodeMode(state.codeMode);bind();els.modeSelect.value=state.mode;populateModels();renderMessages();await loadChats();renderChatList();renderMessages();await checkWebGPU();await loadStudyData();await registerSW();await loadRuntimes();warmOfflineCaches();setConnection(navigator.onLine?(state.mode==="online"?"Online • Gemini":"Offline • cached runtime") : "Offline • no network");if(state.mode==="offline"){els.offlinePanel.classList.remove("hidden");setTimeout(()=>loadRuntimes(),150)}}
init();
