import * as webllm from "https://esm.run/@mlc-ai/web-llm";

const $ = id => document.getElementById(id);
const els = Object.fromEntries(["sidebar","closeSidebarBtn","newChatBtn","chatList","themeBtn","settingsBtn","menuBtn","chatTitle","connectionText","modeSelect","modelSelect","offlinePanel","webgpuStatus","loadModelBtn","freeModelBtn","modelProgress","modelProgressText","messages","welcome","fileInput","attachBtn","promptInput","stopBtn","sendBtn","tokenEstimate","attachmentCard","attachmentName","attachmentStatus","clearAttachmentBtn","settingsModal","closeSettingsBtn","apiKeyInput","instructionsInput","thinkingSelect","exportBtn","saveSettingsBtn","toast"].map(id=>[id,$(id)]));

const ONLINE_MODELS = [
  {id:"gemini-3.8-flash",name:"Gemini 3.8 Flash"},
  {id:"gemini-3.7-flash",name:"Gemini 3.7 Flash"},
  {id:"gemini-3.1-pro-preview",name:"Gemini 3.1 Pro Preview"}
];
const OFFLINE_WANTED = [
  {key:"qwen05",name:"Qwen 2.5 0.5B",terms:["qwen2.5","0.5b","instruct"]},
  {key:"qwen15",name:"Qwen 2.5 1.5B",terms:["qwen2.5","1.5b","instruct"],exclude:["coder"]},
  {key:"coder15",name:"Qwen 2.5 Coder 1.5B",terms:["qwen2.5","coder","1.5b"]},
  {key:"smolvlm",name:"SmolVLM",terms:["smolvlm"],vlm:true}
];
const DEFAULT_INSTRUCTIONS = "You are KinStudy Pro, a helpful study and coding assistant. Explain accurately, show steps when useful, do not invent facts, and distinguish uncertainty. When verified study context is provided, use it only when relevant.";

let state = {
  chats: [], currentId: null, theme: localStorage.getItem("ks_theme") || "dark",
  mode: localStorage.getItem("ks_mode") || "online", onlineModel: localStorage.getItem("ks_online_model") || "gemini-3.8-flash",
  offlineKey: localStorage.getItem("ks_offline_key") || "qwen05", apiKey: localStorage.getItem("ks_api_key") || "",
  instructions: localStorage.getItem("ks_instructions") || "", thinking: localStorage.getItem("ks_thinking") || "medium",
  attachment: null, studyData: [], engine: null, loadedModelId: null, generating: false, aborter: null,
  webgpu: false, offlineCatalog: []
};

function uid(){return crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`}
function saveChats(){localStorage.setItem("ks_chats_v3",JSON.stringify(state.chats))}
function loadChats(){try{state.chats=JSON.parse(localStorage.getItem("ks_chats_v3")||"[]")}catch{state.chats=[]} if(!state.chats.length)newChat(false); else state.currentId=localStorage.getItem("ks_current_chat")||state.chats[0].id}
function currentChat(){return state.chats.find(c=>c.id===state.currentId)}
function toast(msg,ms=2600){els.toast.textContent=msg;els.toast.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.add("hidden"),ms)}
function setTheme(theme){state.theme=theme;document.documentElement.dataset.theme=theme;localStorage.setItem("ks_theme",theme);document.querySelector('meta[name="theme-color"]').content=theme==="light"?"#ffffff":"#111827"}
function escapeHtml(s=""){return s.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function renderMarkdown(text){if(window.marked&&window.DOMPurify){marked.setOptions({gfm:true,breaks:true});return DOMPurify.sanitize(marked.parse(text||""),{ADD_ATTR:["target"]})}return `<p>${escapeHtml(text).replace(/\n/g,"<br>")}</p>`}
function estimateTokens(text=""){return Math.max(0,Math.ceil(text.length/4))}
function updateTokenEstimate(){let n=estimateTokens(els.promptInput.value);if(state.attachment?.text)n+=estimateTokens(state.attachment.text);els.tokenEstimate.textContent=`~${n.toLocaleString()} tokens`}
function autoGrow(){els.promptInput.style.height="auto";els.promptInput.style.height=Math.min(180,els.promptInput.scrollHeight)+"px"}
function setConnection(msg){els.connectionText.textContent=msg}

function newChat(render=true){const c={id:uid(),title:"New chat",created:Date.now(),messages:[]};state.chats.unshift(c);state.currentId=c.id;localStorage.setItem("ks_current_chat",c.id);saveChats();if(render){renderChatList();renderMessages()}}
function deleteChat(id){state.chats=state.chats.filter(c=>c.id!==id);if(!state.chats.length)newChat(false);if(state.currentId===id)state.currentId=state.chats[0].id;localStorage.setItem("ks_current_chat",state.currentId);saveChats();renderChatList();renderMessages()}
function selectChat(id){state.currentId=id;localStorage.setItem("ks_current_chat",id);renderChatList();renderMessages();els.sidebar.classList.remove("open")}
function renderChatList(){els.chatList.innerHTML="";for(const c of state.chats){const row=document.createElement("div");row.className="chat-item"+(c.id===state.currentId?" active":"");row.innerHTML=`<button class="chat-open">${escapeHtml(c.title)}</button><button class="chat-delete" title="Delete">×</button>`;row.querySelector(".chat-open").onclick=()=>selectChat(c.id);row.querySelector(".chat-delete").onclick=()=>deleteChat(c.id);els.chatList.append(row)}}
function addMessage(role,content,meta={}){const c=currentChat();const m={id:uid(),role,content,created:Date.now(),...meta};c.messages.push(m);if(role==="user"&&c.title==="New chat")c.title=content.replace(/\s+/g," ").slice(0,42)||"New chat";saveChats();renderChatList();return m}
function renderMessages(){const c=currentChat();els.chatTitle.textContent=c?.title||"New chat";els.messages.querySelectorAll(".message").forEach(x=>x.remove());els.welcome.classList.toggle("hidden",!!c?.messages.length);for(const m of c?.messages||[])appendMessageElement(m);scrollBottom()}
function appendMessageElement(m){const el=document.createElement("article");el.className=`message ${m.role}`;el.dataset.id=m.id;el.innerHTML=`<div class="avatar">${m.role==="user"?"Y":"K"}</div><div class="message-body"><div class="message-head">${m.role==="user"?"You":"KinStudy"}</div><div class="message-content">${renderMarkdown(m.content)}</div>${m.attachmentName?`<div class="attachment-inline">📎 ${escapeHtml(m.attachmentName)}</div>`:""}</div>`;els.messages.append(el);wireCopyButtons(el)}
function wireCopyButtons(root){root.querySelectorAll("pre").forEach(pre=>{if(pre.querySelector(".copy-code"))return;const b=document.createElement("button");b.className="copy-code";b.textContent="Copy code";b.onclick=async()=>{await navigator.clipboard.writeText(pre.querySelector("code")?.innerText||pre.innerText);b.textContent="Copied";setTimeout(()=>b.textContent="Copy code",1200)};pre.append(b)})}
function updateMessage(m){const el=els.messages.querySelector(`[data-id="${m.id}"] .message-content`);if(el){el.innerHTML=renderMarkdown(m.content);wireCopyButtons(el.parentElement);scrollBottom()}}
function scrollBottom(){requestAnimationFrame(()=>els.messages.scrollTop=els.messages.scrollHeight)}

function resolveOfflineCatalog(){const list=webllm.prebuiltAppConfig?.model_list||[];state.offlineCatalog=OFFLINE_WANTED.map(w=>{const hit=list.find(r=>{const id=(r.model_id||"").toLowerCase();return w.terms.every(t=>id.includes(t))&&!(w.exclude||[]).some(t=>id.includes(t))&&(w.vlm?String(r.model_type).toLowerCase().includes("vlm")||id.includes("vlm"):true)});return {...w,modelId:hit?.model_id||null,record:hit||null}})}
function populateModels(){els.modelSelect.innerHTML="";if(state.mode==="online"){for(const m of ONLINE_MODELS)els.modelSelect.add(new Option(m.name,m.id));els.modelSelect.value=ONLINE_MODELS.some(x=>x.id===state.onlineModel)?state.onlineModel:ONLINE_MODELS[0].id}else{for(const m of state.offlineCatalog){const suffix=m.modelId?"":" — unavailable";els.modelSelect.add(new Option(m.name+suffix,m.key));}els.modelSelect.value=state.offlineCatalog.some(x=>x.key===state.offlineKey)?state.offlineKey:state.offlineCatalog[0]?.key}els.offlinePanel.classList.toggle("hidden",state.mode!=="offline")}
async function checkWebGPU(){if(!navigator.gpu){state.webgpu=false;els.webgpuStatus.textContent="WebGPU unavailable in this browser";return}try{const adapter=await navigator.gpu.requestAdapter();state.webgpu=!!adapter;els.webgpuStatus.textContent=adapter?"WebGPU ready":"No compatible GPU adapter"}catch(e){state.webgpu=false;els.webgpuStatus.textContent=`WebGPU check failed: ${e.message}`}}
async function loadOfflineModel(){if(!state.webgpu)return toast("WebGPU is not available here.");const cfg=state.offlineCatalog.find(x=>x.key===state.offlineKey);if(!cfg?.modelId)return toast("That model is not in this WebLLM build. Choose an available model.",4000);if(state.generating)return;try{els.loadModelBtn.disabled=true;els.modelProgress.style.width="2%";els.modelProgressText.textContent="Preparing engine…";if(state.engine&&state.loadedModelId!==cfg.modelId){try{await state.engine.unload()}catch{}state.engine=null;state.loadedModelId=null}state.engine=await webllm.CreateMLCEngine(cfg.modelId,{initProgressCallback:p=>{const pct=Math.max(1,Math.round((p.progress||0)*100));els.modelProgress.style.width=pct+"%";els.modelProgressText.textContent=p.text||`Loading ${pct}%`}});state.loadedModelId=cfg.modelId;els.modelProgress.style.width="100%";els.modelProgressText.textContent=`Loaded: ${cfg.modelId}`;els.freeModelBtn.disabled=false;setConnection("Offline engine ready");toast("Offline model loaded") }catch(e){console.error(e);state.engine=null;state.loadedModelId=null;els.modelProgressText.textContent=`Load failed: ${friendlyError(e)}`;toast("Model load failed",3500)}finally{els.loadModelBtn.disabled=false}}
async function freeOfflineModel(){try{if(state.engine?.unload)await state.engine.unload()}catch(e){console.warn(e)}state.engine=null;state.loadedModelId=null;els.freeModelBtn.disabled=true;els.modelProgress.style.width="0";els.modelProgressText.textContent="Engine released from memory.";setConnection("Offline model not loaded")}

async function loadStudyData(){try{const r=await fetch("./study-data.json",{cache:"no-cache"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();state.studyData=Array.isArray(j)?j:(j.entries||[])}catch(e){console.warn("study-data unavailable",e);state.studyData=[]}}
function relevantStudyContext(query){const q=query.toLowerCase();const words=new Set(q.match(/[a-z0-9²]+/g)||[]);return state.studyData.map(e=>{let score=0;for(const k of e.keywords||[]){const kl=k.toLowerCase();if(q.includes(kl))score+=4;for(const w of kl.split(/\s+/))if(words.has(w)&&w.length>3)score++}return {e,score}}).filter(x=>x.score>=3).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>`[${x.e.subject}: ${x.e.title}] ${x.e.content}`).join("\n")}

async function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}
async function readPDF(file){els.attachmentStatus.textContent="Loading PDF engine…";const pdfjs=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs");pdfjs.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";const data=new Uint8Array(await file.arrayBuffer());const pdf=await pdfjs.getDocument({data}).promise;let text="";for(let i=1;i<=pdf.numPages;i++){els.attachmentStatus.textContent=`Reading PDF: Page ${i} of ${pdf.numPages}…`;const page=await pdf.getPage(i);const content=await page.getTextContent();text+=`\n\n--- Page ${i} ---\n`+content.items.map(x=>x.str).join(" ");await new Promise(r=>requestAnimationFrame(r))}els.attachmentStatus.textContent="Extracting text tokens…";return text.trim()}
async function handleFile(file){if(!file)return;state.attachment={file,name:file.name,type:file.type||"",text:null,dataUrl:null};els.attachmentName.textContent=file.name;els.attachmentStatus.textContent="Reading file…";els.attachmentCard.classList.remove("hidden");try{if(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")){state.attachment.text=await readPDF(file);els.attachmentStatus.textContent=`PDF ready • ~${estimateTokens(state.attachment.text).toLocaleString()} tokens`}else if(file.type.startsWith("image/")){state.attachment.dataUrl=await fileToDataURL(file);els.attachmentStatus.textContent="Image ready"}else{state.attachment.text=await file.text();els.attachmentStatus.textContent=`Text ready • ~${estimateTokens(state.attachment.text).toLocaleString()} tokens`}updateTokenEstimate()}catch(e){console.error(e);els.attachmentStatus.textContent=`Could not read file: ${friendlyError(e)}`}}
function clearAttachment(){state.attachment=null;els.fileInput.value="";els.attachmentCard.classList.add("hidden");updateTokenEstimate()}

function buildSystem(userText){const study=relevantStudyContext(userText);return [DEFAULT_INSTRUCTIONS,state.instructions?`User custom instructions:\n${state.instructions}`:"",study?`Verified local study context (use only if relevant):\n${study}`:""].filter(Boolean).join("\n\n")}
function chatHistoryForGemini(){return (currentChat()?.messages||[]).slice(-18).filter(m=>m.content).map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}))}
function dataUrlParts(dataUrl){const m=dataUrl.match(/^data:([^;]+);base64,(.+)$/);return m?{mimeType:m[1],data:m[2]}:null}
async function generateOnline(userText,assistantMsg,attachment){if(!state.apiKey)throw new Error("Add your Gemini API key in Settings first.");const system=buildSystem(userText);const contents=chatHistoryForGemini();const last=contents[contents.length-1];if(attachment?.text)last.parts.push({text:`\n\nAttached file (${attachment.name}):\n${attachment.text}`});if(attachment?.dataUrl){const d=dataUrlParts(attachment.dataUrl);if(d)last.parts.push({inlineData:d})}els.attachmentStatus.textContent=attachment?"Sending context to model…":"";state.aborter=new AbortController();const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(state.onlineModel)}:streamGenerateContent?alt=sse`;
  const response=await fetch(endpoint,{method:"POST",signal:state.aborter.signal,headers:{"Content-Type":"application/json","x-goog-api-key":state.apiKey},body:JSON.stringify({system_instruction:{parts:[{text:system}]},contents,generationConfig:{thinkingConfig:{thinkingLevel:state.thinking}}})});
  if(!response.ok){let detail="";try{detail=(await response.json())?.error?.message||""}catch{}throw new Error(`Gemini ${response.status}${detail?`: ${detail}`:""}`)}
  const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split("\n\n");buffer=blocks.pop()||"";for(const block of blocks){for(const line of block.split("\n")){if(!line.startsWith("data:"))continue;const raw=line.slice(5).trim();if(!raw||raw==="[DONE]")continue;try{const obj=JSON.parse(raw);const txt=(obj.candidates?.[0]?.content?.parts||[]).map(p=>p.text||"").join("");if(txt){assistantMsg.content+=txt;updateMessage(assistantMsg)}}catch(e){console.warn("SSE parse",e)}}}}saveChats()}
function offlineMessages(userText,attachment){const system=buildSystem(userText);const history=(currentChat()?.messages||[]).slice(-16,-1).map(m=>({role:m.role==="assistant"?"assistant":"user",content:m.content}));let content=userText;if(attachment?.text)content+=`\n\nAttached file (${attachment.name}):\n${attachment.text}`;if(attachment?.dataUrl){const cfg=state.offlineCatalog.find(x=>x.key===state.offlineKey);if(!cfg?.vlm)throw new Error("This offline text model cannot read images. Use Online mode or an available offline VLM.");content=[{type:"text",text:userText},{type:"image_url",image_url:{url:attachment.dataUrl}}]}return [{role:"system",content:system},...history,{role:"user",content}]}
async function generateOffline(userText,assistantMsg,attachment){const cfg=state.offlineCatalog.find(x=>x.key===state.offlineKey);if(!cfg?.modelId)throw new Error("Selected offline model is unavailable in this WebLLM build.");if(!state.engine||state.loadedModelId!==cfg.modelId)throw new Error("Load the selected offline engine first.");const stream=await state.engine.chat.completions.create({messages:offlineMessages(userText,attachment),stream:true,max_tokens:1024,temperature:0.6});for await(const chunk of stream){if(!state.generating)break;const delta=chunk.choices?.[0]?.delta?.content||"";if(delta){assistantMsg.content+=delta;updateMessage(assistantMsg)}}saveChats()}

async function sendMessage(forcedText=null){const text=(forcedText??els.promptInput.value).trim();if(!text||state.generating)return;const attachment=state.attachment;els.promptInput.value="";autoGrow();updateTokenEstimate();const userMsg=addMessage("user",text,{attachmentName:attachment?.name||null});els.welcome.classList.add("hidden");appendMessageElement(userMsg);const assistantMsg=addMessage("assistant","");appendMessageElement(assistantMsg);state.generating=true;els.sendBtn.disabled=true;els.stopBtn.classList.remove("hidden");setConnection(state.mode==="online"?"Gemini is responding…":"Offline model is responding…");try{if(state.mode==="online")await generateOnline(text,assistantMsg,attachment);else await generateOffline(text,assistantMsg,attachment);if(!assistantMsg.content)assistantMsg.content="No text response was returned."}catch(e){if(e?.name==="AbortError")assistantMsg.content+=(assistantMsg.content?"\n\n":"")+"_Generation stopped._";else assistantMsg.content+=(assistantMsg.content?"\n\n":"")+`**Error:** ${friendlyError(e)}`;console.error(e)}finally{state.generating=false;state.aborter=null;els.sendBtn.disabled=false;els.stopBtn.classList.add("hidden");updateMessage(assistantMsg);saveChats();clearAttachment();setConnection(state.mode==="online"?"Online • Gemini":"Offline"+ (state.loadedModelId?" • engine ready":" • engine not loaded"))}}
function stopGeneration(){state.generating=false;state.aborter?.abort();try{state.engine?.interruptGenerate?.()}catch{}}
function friendlyError(e){const s=String(e?.message||e||"Unknown error");if(/out of memory|device lost|buffer/i.test(s))return `${s} Try a smaller offline model, then Free RAM and reload.`;if(/failed to fetch|network/i.test(s))return `${s} Check internet access for first-time model/API downloads.`;return s}

function openSettings(){els.apiKeyInput.value=state.apiKey;els.instructionsInput.value=state.instructions;els.thinkingSelect.value=state.thinking;els.settingsModal.classList.remove("hidden")}
function saveSettings(){state.apiKey=els.apiKeyInput.value.trim();state.instructions=els.instructionsInput.value.trim();state.thinking=els.thinkingSelect.value;localStorage.setItem("ks_api_key",state.apiKey);localStorage.setItem("ks_instructions",state.instructions);localStorage.setItem("ks_thinking",state.thinking);els.settingsModal.classList.add("hidden");toast("Settings saved")}
function exportChat(){const c=currentChat();const md=`# ${c.title}\n\n`+(c.messages||[]).map(m=>`## ${m.role==="user"?"You":"KinStudy"}\n\n${m.content}`).join("\n\n");const blob=new Blob([md],{type:"text/markdown"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${c.title.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"")||"kinstudy-chat"}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function bind(){els.newChatBtn.onclick=()=>newChat();els.menuBtn.onclick=()=>els.sidebar.classList.add("open");els.closeSidebarBtn.onclick=()=>els.sidebar.classList.remove("open");els.themeBtn.onclick=()=>setTheme(state.theme==="dark"?"light":"dark");els.settingsBtn.onclick=openSettings;els.closeSettingsBtn.onclick=()=>els.settingsModal.classList.add("hidden");els.saveSettingsBtn.onclick=saveSettings;els.exportBtn.onclick=exportChat;els.settingsModal.onclick=e=>{if(e.target===els.settingsModal)els.settingsModal.classList.add("hidden")};els.attachBtn.onclick=()=>els.fileInput.click();els.fileInput.onchange=()=>handleFile(els.fileInput.files[0]);els.clearAttachmentBtn.onclick=clearAttachment;els.sendBtn.onclick=()=>sendMessage();els.stopBtn.onclick=stopGeneration;els.promptInput.oninput=()=>{autoGrow();updateTokenEstimate()};els.promptInput.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}};document.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>sendMessage(b.dataset.prompt));els.modeSelect.onchange=()=>{state.mode=els.modeSelect.value;localStorage.setItem("ks_mode",state.mode);populateModels();setConnection(state.mode==="online"?"Online • Gemini":"Offline"+(state.loadedModelId?" • engine ready":" • engine not loaded"))};els.modelSelect.onchange=()=>{if(state.mode==="online"){state.onlineModel=els.modelSelect.value;localStorage.setItem("ks_online_model",state.onlineModel)}else{state.offlineKey=els.modelSelect.value;localStorage.setItem("ks_offline_key",state.offlineKey);if(state.loadedModelId)els.modelProgressText.textContent="Model selection changed. Press Load Engine to switch."}};els.loadModelBtn.onclick=loadOfflineModel;els.freeModelBtn.onclick=freeOfflineModel}
async function registerSW(){if("serviceWorker" in navigator&&location.protocol.startsWith("http")){try{await navigator.serviceWorker.register("./sw.js");console.log("Service worker registered")}catch(e){console.warn("SW registration failed",e)}}}
async function init(){setTheme(state.theme);resolveOfflineCatalog();loadChats();bind();renderChatList();renderMessages();els.modeSelect.value=state.mode;populateModels();await Promise.all([checkWebGPU(),loadStudyData(),registerSW()]);setConnection(state.mode==="online"?"Online • Gemini":"Offline • engine not loaded")}
init();
